/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import conexion.conectarBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramon
 */
public class Admin_Menu extends javax.swing.JFrame {
    
    conectarBD con = new conectarBD();
    Connection cn=con.conectar();

    /**
     * Creates new form Alta_Empleados
     */
    public Admin_Menu() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarMenu("");
        mostrarTam("");
    }
    
    void mostrarTam (String ident){
       DefaultTableModel modeloTam = new DefaultTableModel();
        modeloTam.addColumn("Numero");
        modeloTam.addColumn("Tamaño");
        modeloTam.addColumn("Costo"); 
        tabInfoTam.setModel(modeloTam);
        String sql="";
        
        if(ident.equals("")){
            sql="SELECT * FROM tamanios";
        }
        else{
            sql="SELECT * FROM tamanios WHERE idTam='"+ident+"'";
        }
        
        String []datos =  new String[3];
        
        try {
            Statement dst= cn.createStatement();
            ResultSet rs = dst.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                modeloTam.addRow(datos);
            }
            tabInfoTam.setModel(modeloTam);
            
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    void mostrarMenu (String identificador){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Producto");
        modelo.addColumn("Tipo");
        modelo.addColumn("Precio");
        modelo.addColumn("Disponible");
        jTableMenu.setModel(modelo);
        String sql="";
        if(identificador.equals("")){
            sql="SELECT * FROM productos";
        }
        else{
            sql="SELECT * FROM productos WHERE idProd='"+identificador+"'";
        }
        
        String []datos =  new String[5];
        
        try {
            Statement dst= cn.createStatement();
            ResultSet rs = dst.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                modelo.addRow(datos);
            }
            jTableMenu.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        PanelAlta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        chkDisponible = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        PanelActualizar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chkDisponible2 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        PanelTamanios = new javax.swing.JPanel();
        MAltaTam = new javax.swing.JPanel();
        lblAlta = new javax.swing.JLabel();
        MModTam = new javax.swing.JPanel();
        lblMod = new javax.swing.JLabel();
        PanelAltaTam = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNomTam = new javax.swing.JTextField();
        txtPrecTam = new javax.swing.JTextField();
        btnAltaTam = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        PanelModTam = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtBuscarTam = new javax.swing.JTextField();
        btnBuscarTam = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabInfoTam = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNuevNom = new javax.swing.JTextField();
        txtNuevPrec = new javax.swing.JTextField();
        btnModTam = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MAlta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MActualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MTamanios = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 252, 242));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 252, 242));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/x.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menos.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        PanelAlta.setBackground(new java.awt.Color(255, 252, 242));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("ALTA PRODUCTO");

        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btnAlta.png"))); // NOI18N
        btnAlta.setContentAreaFilled(false);
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("ID");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Precio");

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        chkDisponible.setBackground(new java.awt.Color(255, 252, 242));
        chkDisponible.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDisponible.setText("Disponible");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tipo");

        cmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida Caliente", "Bebida Fría", "Repostería" }));
        cmbTipo.setToolTipText("");

        javax.swing.GroupLayout PanelAltaLayout = new javax.swing.GroupLayout(PanelAlta);
        PanelAlta.setLayout(PanelAltaLayout);
        PanelAltaLayout.setHorizontalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAltaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAltaLayout.createSequentialGroup()
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel11))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAltaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386))))
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel8))
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(chkDisponible)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAltaLayout.setVerticalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(chkDisponible)
                .addGap(18, 18, 18)
                .addComponent(btnAlta)
                .addGap(24, 24, 24))
        );

        PanelActualizar.setBackground(new java.awt.Color(255, 252, 242));
        PanelActualizar.setPreferredSize(new java.awt.Dimension(597, 418));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Id producto");

        txtIdProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("ACTUALIZAR PRODUCTO");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btnActualizar.png"))); // NOI18N
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nuevo precio");

        txtNPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Info producto");

        chkDisponible2.setBackground(new java.awt.Color(255, 252, 242));
        chkDisponible2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDisponible2.setText("Disponible");

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMenu);

        javax.swing.GroupLayout PanelActualizarLayout = new javax.swing.GroupLayout(PanelActualizar);
        PanelActualizar.setLayout(PanelActualizarLayout);
        PanelActualizarLayout.setHorizontalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActualizarLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addComponent(txtNPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(chkDisponible2))
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelActualizarLayout.setVerticalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(81, 81, 81))
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(chkDisponible2))
                .addGap(32, 32, 32)
                .addComponent(btnActualizar)
                .addGap(26, 26, 26))
        );

        PanelTamanios.setBackground(new java.awt.Color(255, 252, 242));
        PanelTamanios.setPreferredSize(new java.awt.Dimension(597, 418));

        MAltaTam.setBackground(new java.awt.Color(255, 252, 242));
        MAltaTam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 113, 72)));
        MAltaTam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAltaTam.setPreferredSize(new java.awt.Dimension(165, 32));
        MAltaTam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAltaTamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MAltaTamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MAltaTamMouseExited(evt);
            }
        });
        MAltaTam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAlta.setText("AÑADIR TAMAÑO");
        MAltaTam.add(lblAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 8, 160, -1));

        MModTam.setBackground(new java.awt.Color(255, 252, 242));
        MModTam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 113, 72)));
        MModTam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MModTam.setPreferredSize(new java.awt.Dimension(165, 32));
        MModTam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MModTamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MModTamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MModTamMouseExited(evt);
            }
        });
        MModTam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMod.setText("MODIFICAR TAMAÑO");
        MModTam.add(lblMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 8, -1, -1));

        PanelAltaTam.setBackground(new java.awt.Color(255, 252, 242));
        PanelAltaTam.setPreferredSize(new java.awt.Dimension(725, 350));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Nombre");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Precio por tamaño");

        txtNomTam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPrecTam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAltaTam.setText("AÑADIR TAMAÑO");
        btnAltaTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaTamActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("AÑADIR TAMAÑO");

        javax.swing.GroupLayout PanelAltaTamLayout = new javax.swing.GroupLayout(PanelAltaTam);
        PanelAltaTam.setLayout(PanelAltaTamLayout);
        PanelAltaTamLayout.setHorizontalGroup(
            PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaTamLayout.createSequentialGroup()
                .addGroup(PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaTamLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecTam, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomTam, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAltaTam)))
                    .addGroup(PanelAltaTamLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAltaTamLayout.setVerticalGroup(
            PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaTamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(54, 54, 54)
                .addGroup(PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(PanelAltaTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(43, 43, 43)
                .addComponent(btnAltaTam)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        PanelModTam.setBackground(new java.awt.Color(255, 252, 242));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Nombre");

        txtBuscarTam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnBuscarTam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        btnBuscarTam.setText("Buscar");
        btnBuscarTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTamActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setText("MODIFICAR TAMAÑO");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Info tamaño");

        tabInfoTam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabInfoTam);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Nuevo precio");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Nuevo nombre");

        txtNuevNom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNuevPrec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnModTam.setText("MODIFICAR TAMAÑO");
        btnModTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModTamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModTamLayout = new javax.swing.GroupLayout(PanelModTam);
        PanelModTam.setLayout(PanelModTamLayout);
        PanelModTamLayout.setHorizontalGroup(
            PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModTamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModTamLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(256, 256, 256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModTamLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarTam, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarTam)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModTamLayout.createSequentialGroup()
                        .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevNom, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197))))
            .addGroup(PanelModTamLayout.createSequentialGroup()
                .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModTamLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel24))
                    .addGroup(PanelModTamLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelModTamLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btnModTam)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelModTamLayout.setVerticalGroup(
            PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModTamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarTam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtBuscarTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtNuevNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtNuevPrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModTam)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelTamaniosLayout = new javax.swing.GroupLayout(PanelTamanios);
        PanelTamanios.setLayout(PanelTamaniosLayout);
        PanelTamaniosLayout.setHorizontalGroup(
            PanelTamaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTamaniosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(MAltaTam, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MModTam, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(PanelAltaTam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addComponent(PanelModTam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelTamaniosLayout.setVerticalGroup(
            PanelTamaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTamaniosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelTamaniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAltaTam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MModTam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelAltaTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelModTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close)
                .addContainerGap())
            .addComponent(PanelAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addComponent(PanelTamanios, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(min)
                    .addComponent(close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTamanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 451));

        jPanel2.setBackground(new java.awt.Color(164, 113, 72));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAlta.setBackground(new java.awt.Color(164, 113, 72));
        MAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MAlta.setPreferredSize(new java.awt.Dimension(217, 45));
        MAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MAltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MAltaMouseExited(evt);
            }
        });
        MAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alta productos");
        MAlta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MAlta.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(MAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 50));

        MActualizar.setBackground(new java.awt.Color(164, 113, 72));
        MActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MActualizar.setPreferredSize(new java.awt.Dimension(217, 45));
        MActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MActualizarMouseExited(evt);
            }
        });
        MActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar menu");
        MActualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MActualizar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(MActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logos.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        MTamanios.setBackground(new java.awt.Color(164, 113, 72));
        MTamanios.setPreferredSize(new java.awt.Dimension(217, 45));
        MTamanios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MTamaniosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MTamaniosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MTamaniosMouseExited(evt);
            }
        });
        MTamanios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tamaños");
        MTamanios.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MTamanios.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(MTamanios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 451));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaMouseClicked
        MAlta.setBackground(new Color(174,123,82));
        MActualizar.setBackground(new Color(164,113,72));
        MTamanios.setBackground(new Color(164,113,72));
        
        PanelAlta.setVisible(true);
        PanelActualizar.setVisible(false);
        PanelTamanios.setVisible(false);
    }//GEN-LAST:event_MAltaMouseClicked

    private void MActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActualizarMouseClicked
        MAlta.setBackground(new Color(164,113,72));
        MActualizar.setBackground(new Color(174,123,82));
        MTamanios.setBackground(new Color(164,113,72));
        
        PanelAlta.setVisible(false);
        PanelActualizar.setVisible(true);
        PanelTamanios.setVisible(false);
    }//GEN-LAST:event_MActualizarMouseClicked

    private void MAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaMouseEntered
        MAlta.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MAltaMouseEntered

    private void MActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActualizarMouseEntered
        MActualizar.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MActualizarMouseEntered

    private void MAltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaMouseExited
        MAlta.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MAltaMouseExited

    private void MActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActualizarMouseExited
        MActualizar.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MActualizarMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(Menu_Administrador.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        Menu_Administrador obj = new Menu_Administrador();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String disponible;
        if(chkDisponible2.isSelected())
        {
            disponible="Si";
        }else{
            disponible="No";
        }
        
        try {
            
            Statement astmt = cn.createStatement();
            astmt.executeLargeUpdate("UPDATE productos SET Precio='"+txtNPrecio.getText()+"', Disponibilidad='"+disponible+"' WHERE idProd='"+txtIdProd.getText()+"'");
            mostrarMenu(txtIdProd.getText());
            
            JOptionPane.showMessageDialog(null, "Producto actualizado correctamente");
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        String disponible;
        if(chkDisponible.isSelected())
        {
            disponible="Si";
        }else{
            disponible="No";
        }
        
        try {
            
            Statement stmt = cn.createStatement();
            stmt.executeLargeUpdate("INSERT INTO productos VALUES ('"+txtId.getText()+"','"+txtNombre.getText()+"','"+cmbTipo.getSelectedItem()+"','"+txtPrecio.getText()+"','"+disponible+"')");
            //mostrarDatos("");
            JOptionPane.showMessageDialog(null, "Producto agregado correctamente");
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        mostrarMenu(txtIdProd.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void MAltaTamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaTamMouseEntered
        MAltaTam.setBackground(new Color(164,113,72));
        MAltaTam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164,113,72)));
        lblAlta.setForeground(new Color(255,252,242));
    }//GEN-LAST:event_MAltaTamMouseEntered

    private void MAltaTamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaTamMouseExited
        MAltaTam.setBackground(new Color(255,252,242));
        MAltaTam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164,113,72)));
        lblAlta.setForeground(Color.BLACK);
    }//GEN-LAST:event_MAltaTamMouseExited

    private void MModTamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MModTamMouseEntered
        /*MModTam.setBackground(new Color(164,113,712));
        MModTam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164,113,72)));
        lblMod.setForeground(new Color(255,252,242));*/
    }//GEN-LAST:event_MModTamMouseEntered

    private void MModTamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MModTamMouseExited
        /*MModTam.setBackground(new Color(255,252,242));
        MModTam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164,113,72)));
        lblMod.setForeground(Color.BLACK);*/
    }//GEN-LAST:event_MModTamMouseExited

    private void MTamaniosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTamaniosMouseEntered
        MTamanios.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MTamaniosMouseEntered

    private void MTamaniosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTamaniosMouseExited
        MTamanios.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MTamaniosMouseExited

    private void MTamaniosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTamaniosMouseClicked
        MAlta.setBackground(new Color(164,113,72));
        MActualizar.setBackground(new Color(164,113,72));
        MTamanios.setBackground(new Color(174,123,82));
        
        PanelAlta.setVisible(false);
        PanelActualizar.setVisible(false);
        PanelTamanios.setVisible(true);
    }//GEN-LAST:event_MTamaniosMouseClicked

    private void MAltaTamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaTamMouseClicked
        MAltaTam.setBackground(new Color(164,113,72));
        PanelAltaTam.setVisible(true);
        PanelModTam.setVisible(false);
    }//GEN-LAST:event_MAltaTamMouseClicked

    private void MModTamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MModTamMouseClicked
        MModTam.setBackground(new Color(164,113,72));
        PanelAltaTam.setVisible(false);
        PanelModTam.setVisible(true);
    }//GEN-LAST:event_MModTamMouseClicked

    private void btnAltaTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaTamActionPerformed
        // TODO add your handling code here:
          String disponible;
        
        if(chkDisponible.isSelected()){
            disponible="Si";
        }else{
            disponible="No";
        }
        
        try {
            Statement stmt = cn.createStatement();
            stmt.executeLargeUpdate("INSERT INTO tamanios (NombreTam,Costo) VALUES ('"+txtNomTam.getText()+"','"+txtPrecTam.getText()+"')");
            JOptionPane.showMessageDialog(null,"Producto agregado correctamente");
        }catch(SQLException ex){
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_btnAltaTamActionPerformed

    private void btnBuscarTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTamActionPerformed
        // TODO add your handling code here:
        mostrarTam(txtBuscarTam.getText());
    }//GEN-LAST:event_btnBuscarTamActionPerformed

    private void btnModTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModTamActionPerformed
        // TODO add your handling code here:  
        try {
            
            Statement astmt = cn.createStatement();
            astmt.executeLargeUpdate("UPDATE tamanios SET NombreTam='"+txtNuevNom.getText()+"', Costo='"+txtNuevPrec.getText()+"' WHERE idTam='"+txtBuscarTam.getText()+"'");
            mostrarTam(txtBuscarTam.getText());
            
            JOptionPane.showMessageDialog(null, "Tamaño actualizado correctamente");
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModTamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MActualizar;
    private javax.swing.JPanel MAlta;
    private javax.swing.JPanel MAltaTam;
    private javax.swing.JPanel MModTam;
    private javax.swing.JPanel MTamanios;
    private javax.swing.JPanel PanelActualizar;
    private javax.swing.JPanel PanelAlta;
    private javax.swing.JPanel PanelAltaTam;
    private javax.swing.JPanel PanelModTam;
    private javax.swing.JPanel PanelTamanios;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAltaTam;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarTam;
    private javax.swing.JButton btnModTam;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkDisponible;
    private javax.swing.JCheckBox chkDisponible2;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMenu;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblMod;
    private javax.swing.JLabel min;
    private javax.swing.JTable tabInfoTam;
    private javax.swing.JTextField txtBuscarTam;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtNPrecio;
    private javax.swing.JTextField txtNomTam;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevNom;
    private javax.swing.JTextField txtNuevPrec;
    private javax.swing.JTextField txtPrecTam;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
