/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import conexion.conectarBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;*/
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/**
 *
 * @author Ramon
 */
public class Inventario extends javax.swing.JFrame {

    conectarBD con = new conectarBD();
    Connection cn=con.conectar();
     PreparedStatement pss;
    ResultSet rs;
    /**
     * Creates new form Alta_Empleados
     */
    private void limpiarcajas()
    {
       txtNCupon.setText(null);
       txtDescuento.setText(null);
       txtCantidad.setText(null);
       txtFechaAdq.setText(null);
       txtNdesc.setText(null);
       txtcup.setText(null);
       
       
    }
   
    
    public Inventario() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarDatos("");
        MostrarCupones();
        
    }
    
    void mostrarDatos (String identificador){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha Adqu.");
        modelo.addColumn("Tipo");
        modelo.addColumn("Stock");
        jTableAct.setModel(modelo);
        String sql="";
        if(identificador.equals("")){
            sql="SELECT * FROM inventario";
        }
        else{
            sql="SELECT * FROM inventario WHERE idInv='"+identificador+"'";
        }
        
        String []datos =  new String[5];
        
        try {
            Statement dst= cn.createStatement();
            ResultSet rs = dst.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                modelo.addRow(datos);
            }
            jTableAct.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        MReporte1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        PanelAlta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtFechaAdq = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        PanelActualizar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIdprod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAct = new javax.swing.JTable();
        PanelReportes = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        PanelCupones = new javax.swing.JPanel();
        MActualizarCup = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        MAltaCup = new javax.swing.JPanel();
        lblAlta = new javax.swing.JLabel();
        PanelActCup = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtcup = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radact = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNdesc = new javax.swing.JTextField();
        PanelAltaCup = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNCupon = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        radActivo = new javax.swing.JCheckBox();
        btnAltaC = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MAlta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MBaja = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MCupones = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        MReporte = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        MReporte1.setBackground(new java.awt.Color(164, 113, 72));
        MReporte1.setPreferredSize(new java.awt.Dimension(217, 45));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Generar reporte");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N

        javax.swing.GroupLayout MReporte1Layout = new javax.swing.GroupLayout(MReporte1);
        MReporte1.setLayout(MReporte1Layout);
        MReporte1Layout.setHorizontalGroup(
            MReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MReporte1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(26, 26, 26))
        );
        MReporte1Layout.setVerticalGroup(
            MReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MReporte1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MReporte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 252, 242));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 252, 242));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/x.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menos.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        PanelAlta.setBackground(new java.awt.Color(255, 252, 242));
        PanelAlta.setPreferredSize(new java.awt.Dimension(597, 418));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de adquisicion");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtFechaAdq.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("ALTA PRODUCTOS");

        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btnAlta.png"))); // NOI18N
        btnAlta.setContentAreaFilled(false);
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("ID");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Tipo");

        cmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DESECHABLES", "CAFE", "TES", "LACTEOS", "REPOSTERIA", "SABORIZANTES", "COMPLEMENTOS", "SUMINISTROS", " " }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Cantidad");

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout PanelAltaLayout = new javax.swing.GroupLayout(PanelAlta);
        PanelAlta.setLayout(PanelAltaLayout);
        PanelAltaLayout.setHorizontalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAltaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(263, 263, 263))
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaAdq, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAltaLayout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(25, 25, 25)
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        PanelAltaLayout.setVerticalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaAdq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addComponent(btnAlta)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PanelActualizar.setBackground(new java.awt.Color(255, 252, 242));
        PanelActualizar.setPreferredSize(new java.awt.Dimension(597, 418));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Id producto");

        txtIdprod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("ACTUALIZAR");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btnActualizar.png"))); // NOI18N
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nuevo stock");

        txtNStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Info producto");

        jTableAct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableAct);

        javax.swing.GroupLayout PanelActualizarLayout = new javax.swing.GroupLayout(PanelActualizar);
        PanelActualizar.setLayout(PanelActualizarLayout);
        PanelActualizarLayout.setHorizontalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActualizarLayout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelActualizarLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addComponent(txtIdprod, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNStock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        PanelActualizarLayout.setVerticalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtIdprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(39, 39, 39))
        );

        PanelReportes.setBackground(new java.awt.Color(255, 252, 242));
        PanelReportes.setPreferredSize(new java.awt.Dimension(597, 418));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel26.setText("HACER REPORTES");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BotonReporte.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Selecciona el mes para generar el reporte");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("AL");

        javax.swing.GroupLayout PanelReportesLayout = new javax.swing.GroupLayout(PanelReportes);
        PanelReportes.setLayout(PanelReportesLayout);
        PanelReportesLayout.setHorizontalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addGroup(PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReportesLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelReportesLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel31)
                        .addGap(37, 37, 37)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReportesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReportesLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReportesLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(193, 193, 193))))
        );
        PanelReportesLayout.setVerticalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel26)
                .addGap(54, 54, 54)
                .addComponent(jLabel20)
                .addGap(47, 47, 47)
                .addGroup(PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        PanelCupones.setBackground(new java.awt.Color(255, 252, 242));
        PanelCupones.setPreferredSize(new java.awt.Dimension(597, 418));

        MActualizarCup.setBackground(new java.awt.Color(255, 252, 242));
        MActualizarCup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 113, 72), 2));
        MActualizarCup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MActualizarCup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MActualizarCupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MActualizarCupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MActualizarCupMouseExited(evt);
            }
        });
        MActualizarCup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblActualizar.setText("ACTUALIZAR CUPONES");
        MActualizarCup.add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3, 240, 30));

        MAltaCup.setBackground(new java.awt.Color(255, 252, 242));
        MAltaCup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164, 113, 72), 2));
        MAltaCup.setForeground(new java.awt.Color(164, 113, 72));
        MAltaCup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAltaCup.setPreferredSize(new java.awt.Dimension(165, 32));
        MAltaCup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAltaCupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MAltaCupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MAltaCupMouseExited(evt);
            }
        });
        MAltaCup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAlta.setText("AÑADIR CUPON");
        MAltaCup.add(lblAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, -1, -1));

        PanelActCup.setBackground(new java.awt.Color(255, 252, 242));
        PanelActCup.setPreferredSize(new java.awt.Dimension(727, 350));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Buscar cupon");

        txtcup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Info cupon");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCupon", "NombreCupon", "Descuento", "Validez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("IdCupon");
        }

        radact.setBackground(new java.awt.Color(255, 252, 242));
        radact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radact.setText("Activo");
        radact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radactActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btnActualizar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setText("ACTUALIZAR CUPON");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Nuevo Descuento");

        txtNdesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNdescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelActCupLayout = new javax.swing.GroupLayout(PanelActCup);
        PanelActCup.setLayout(PanelActCupLayout);
        PanelActCupLayout.setHorizontalGroup(
            PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActCupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(239, 239, 239))
            .addGroup(PanelActCupLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelActCupLayout.createSequentialGroup()
                        .addComponent(txtcup, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(PanelActCupLayout.createSequentialGroup()
                        .addComponent(txtNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radact)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelActCupLayout.setVerticalGroup(
            PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActCupLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGroup(PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActCupLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel25))
                    .addGroup(PanelActCupLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(PanelActCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(radact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        PanelAltaCup.setBackground(new java.awt.Color(255, 252, 242));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Nombre cupon");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Descuento");

        txtNCupon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        radActivo.setBackground(new java.awt.Color(255, 252, 242));
        radActivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radActivo.setText("Activo");

        btnAltaC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAltaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btnAlta.png"))); // NOI18N
        btnAltaC.setBorderPainted(false);
        btnAltaC.setOpaque(false);
        btnAltaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaCActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel28.setText("ALTA CUPONES");

        javax.swing.GroupLayout PanelAltaCupLayout = new javax.swing.GroupLayout(PanelAltaCup);
        PanelAltaCup.setLayout(PanelAltaCupLayout);
        PanelAltaCupLayout.setHorizontalGroup(
            PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaCupLayout.createSequentialGroup()
                .addGroup(PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaCupLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAltaCupLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(radActivo))))
                    .addGroup(PanelAltaCupLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel28)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAltaCupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAltaC, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        PanelAltaCupLayout.setVerticalGroup(
            PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaCupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(38, 38, 38)
                .addGroup(PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNCupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(30, 30, 30)
                .addGroup(PanelAltaCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(34, 34, 34)
                .addComponent(radActivo)
                .addGap(18, 18, 18)
                .addComponent(btnAltaC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCuponesLayout = new javax.swing.GroupLayout(PanelCupones);
        PanelCupones.setLayout(PanelCuponesLayout);
        PanelCuponesLayout.setHorizontalGroup(
            PanelCuponesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuponesLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(PanelCuponesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAltaCup, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCuponesLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(MActualizarCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(PanelAltaCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PanelActCup, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        PanelCuponesLayout.setVerticalGroup(
            PanelCuponesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuponesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelCuponesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAltaCup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MActualizarCup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(PanelAltaCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelActCup, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close)
                .addContainerGap())
            .addComponent(PanelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addComponent(PanelCupones, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close)
                    .addComponent(min))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCupones, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 451));

        jPanel2.setBackground(new java.awt.Color(164, 113, 72));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAlta.setBackground(new java.awt.Color(164, 113, 72));
        MAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MAlta.setPreferredSize(new java.awt.Dimension(217, 45));
        MAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MAltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MAltaMouseExited(evt);
            }
        });
        MAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alta productos");
        MAlta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MAlta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(MAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 50));

        MBaja.setBackground(new java.awt.Color(164, 113, 72));
        MBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MBaja.setPreferredSize(new java.awt.Dimension(217, 45));
        MBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MBajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MBajaMouseExited(evt);
            }
        });
        MBaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar inventario");
        MBaja.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MBaja.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(MBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logos.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        MCupones.setBackground(new java.awt.Color(164, 113, 72));
        MCupones.setPreferredSize(new java.awt.Dimension(217, 45));
        MCupones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MCuponesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MCuponesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MCuponesMouseExited(evt);
            }
        });
        MCupones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Admin. cupones");
        MCupones.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 13, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MCupones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 43, -1));

        jPanel2.add(MCupones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 249, 240, 50));

        MReporte.setBackground(new java.awt.Color(164, 113, 72));
        MReporte.setPreferredSize(new java.awt.Dimension(217, 45));
        MReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MReporteMouseExited(evt);
            }
        });
        MReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Generar reporte");
        MReporte.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 13, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/granos-blancoS.png"))); // NOI18N
        MReporte.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 43, -1));

        jPanel2.add(MReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 197, 240, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 451));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaMouseClicked
        MAlta.setBackground(new Color(174,123,82));
        MBaja.setBackground(new Color(164,113,72));
        MReporte.setBackground(new Color(164,113,72));
        MCupones.setBackground(new Color(164,113,72));
        
        PanelAlta.setVisible(true);
        PanelActualizar.setVisible(false);
        PanelReportes.setVisible(false);
        PanelCupones.setVisible(false);
    }//GEN-LAST:event_MAltaMouseClicked

    private void MBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MBajaMouseClicked
        MAlta.setBackground(new Color(164,113,72));
        MBaja.setBackground(new Color(174,123,82));
        MReporte.setBackground(new Color(164,113,72));
        MCupones.setBackground(new Color(164,113,72));
        
        PanelAlta.setVisible(false);
        PanelActualizar.setVisible(true);
        PanelReportes.setVisible(false);
        PanelCupones.setVisible(false);
    }//GEN-LAST:event_MBajaMouseClicked

    private void MAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaMouseEntered
        MAlta.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MAltaMouseEntered

    private void MBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MBajaMouseEntered
        MBaja.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MBajaMouseEntered

    private void MAltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaMouseExited
        MAlta.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MAltaMouseExited

    private void MBajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MBajaMouseExited
        MBaja.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MBajaMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(Menu_Administrador.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        Menu_Administrador obj = new Menu_Administrador();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            
            Statement astmt = cn.createStatement();
            astmt.executeLargeUpdate("UPDATE inventario SET Cantidad='"+txtNStock.getText()+"' WHERE idInv='"+txtIdprod.getText()+"'");
            mostrarDatos(txtIdprod.getText()); 
            JOptionPane.showMessageDialog(null, "Inventario actualizado");
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         mostrarDatos("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        mostrarDatos(txtIdprod.getText());
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void MReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MReporteMouseEntered
        MReporte.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MReporteMouseEntered

    private void MReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MReporteMouseExited
        MReporte.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MReporteMouseExited

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        try {

            Statement stmt = cn.createStatement();
            stmt.executeLargeUpdate("INSERT INTO inventario VALUES ('"+txtId.getText()+"','"+txtNombre.getText()+"','"+txtFechaAdq.getText()+"','"+cmbTipo.getSelectedItem()+"','"+txtCantidad.getText()+"')");
            //mostrarDatos("");
            JOptionPane.showMessageDialog(null, "Producto ingresado en el inventario");
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        mostrarDatos("");
    }//GEN-LAST:event_btnAltaActionPerformed

    private void MReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MReporteMouseClicked
        MAlta.setBackground(new Color(164,113,72));
        MBaja.setBackground(new Color(164,113,72));
        MReporte.setBackground(new Color(174,123,82));
        MCupones.setBackground(new Color(164,113,72));
        
        PanelAlta.setVisible(false);
        PanelActualizar.setVisible(false);
        PanelReportes.setVisible(true);
        PanelCupones.setVisible(false);
    }//GEN-LAST:event_MReporteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Document documento = new Document();
        
        String fecha, mes = null, x=(String) cmbMes.getSelectedItem();
        
        try {
            String ruta=System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(a));
            documento.open();
            
            PdfPTable tabla = new PdfPTable(6);
            tabla.addCell("Id");
            tabla.addCell("Fecha");
            tabla.addCell("Productos");
            tabla.addCell("Cantidad");
            tabla.addCell("Metodo de pago");
            tabla.addCell("Total");
            
            try {
                PreparedStatement pst=cn.prepareStatement("select * from ventas");
                
                ResultSet rs = pst.executeQuery();
                    
                if(rs.next())
                {
                    fecha=rs.getString("FecVenta");
                    mes=fecha.split("/")[1];

                    do
                    {   
                        fecha=rs.getString("FecVenta");
                        mes=fecha.split("/")[1];
                        
                        if(mes.equals(x))
                        {
                           tabla.addCell(rs.getString(1));
                           tabla.addCell(rs.getString(2));
                           tabla.addCell(rs.getString(3));
                           tabla.addCell(rs.getString(4));
                           tabla.addCell(rs.getString(5));
                           tabla.addCell(rs.getString(6));  
                        }
                    }while(rs.next());
                    
                    documento.add(tabla);
                }
            } catch (DocumentException | SQLException e) {
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte creado exitosamente");
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MCuponesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCuponesMouseClicked
        MAlta.setBackground(new Color(164,113,72));
        MBaja.setBackground(new Color(164,113,72));
        MReporte.setBackground(new Color(164,113,72));
        MCupones.setBackground(new Color(174,123,82));
        
        PanelAlta.setVisible(false);
        PanelActualizar.setVisible(false);
        PanelReportes.setVisible(false);
        PanelCupones.setVisible(true);
    }//GEN-LAST:event_MCuponesMouseClicked

    private void MCuponesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCuponesMouseEntered
        MCupones.setBackground(new Color(174,123,82));
    }//GEN-LAST:event_MCuponesMouseEntered

    private void MCuponesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCuponesMouseExited
        MCupones.setBackground(new Color(164,113,72));
    }//GEN-LAST:event_MCuponesMouseExited

    private void MAltaCupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaCupMouseEntered
        MAltaCup.setBackground(new Color(164,113,72));
        MAltaCup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164,113,72)));
        lblAlta.setForeground(new Color(255,252,242));
    }//GEN-LAST:event_MAltaCupMouseEntered

    private void MAltaCupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaCupMouseExited
        MAltaCup.setBackground(new Color(255,252,242));
        lblAlta.setForeground(Color.BLACK);
    }//GEN-LAST:event_MAltaCupMouseExited

    private void MActualizarCupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActualizarCupMouseEntered
        MActualizarCup.setBackground(new Color(164,113,72));
        MActualizarCup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(164,113,72)));
        lblActualizar.setForeground(new Color(255,252,242));
    }//GEN-LAST:event_MActualizarCupMouseEntered

    private void MActualizarCupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActualizarCupMouseExited
        MActualizarCup.setBackground(new Color(255,252,242));

        lblActualizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_MActualizarCupMouseExited

    private void MAltaCupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAltaCupMouseClicked
        MAltaCup.setBackground(new Color(164,113,72));
        PanelAltaCup.setVisible(true);
        PanelActCup.setVisible(false);
    }//GEN-LAST:event_MAltaCupMouseClicked

    private void MActualizarCupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActualizarCupMouseClicked
        MActualizarCup.setBackground(new Color(164,113,72));
        PanelAltaCup.setVisible(false);
        PanelActCup.setVisible(true);
    }//GEN-LAST:event_MActualizarCupMouseClicked

    private void btnAltaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaCActionPerformed
        // TODO add your handling code here:
        String Validez= null;
        
        if(radActivo.isSelected())
        {
            Validez="SI";
        }
        else
        {
            Validez= "NO";
        }
         try {
            pss= cn.prepareStatement("INSERT INTO cupones(NombreCup,Descuento,Validez) VALUES(?,?,?)");
          
            pss.setString(1, txtNCupon.getText());
             pss.setString(2, txtDescuento.getText());
              pss.setString(3, Validez);
              
             int res= pss.executeUpdate();
             
             if(res>0)
             {
                 JOptionPane.showMessageDialog(null, "Cupon guardada");
                 limpiarcajas();
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Error al guardar el cupon");
                 limpiarcajas();
             }
              
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos"+e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnAltaCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String[] titu= {"IdCupon", "NombreCup", "Descuento"};
        String[] registros;
        registros = new String[3];

        DefaultTableModel modelo= new DefaultTableModel(null,titu);

        String sql = "select * FROM cupones";

        try {

            pss = cn.prepareStatement("SELECT * from cupones WHERE NombreCup = ?");
            pss.setString(1, txtcup.getText());

            rs = pss.executeQuery();

            while(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Cupon encontrado");
                registros[0]= rs.getString("idCupon");
                registros[1]= rs.getString("NombreCup");
                registros[2]= rs.getString("Descuento");
         
                modelo.addRow(registros);

            }
            jTable1.setModel(modelo);

            // txtInfoEmp.setText("id: "+rs.getString("idUsuarios")+"\nNombre: "+rs.getString("Nombre")+"\nFechaN: "+rs.getString("FecNac")+"\nSexo:"+rs.getString("Sexo")+"\nPuesto: "+rs.getString("Puesto"));

            /*else
            {
                JOptionPane.showMessageDialog(null, "No existe empleado con esa clave");
            }*/

        } catch (SQLException e) {
            System.err.print(e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      String Valido= null;
        int res=0;
        if(radact.isSelected())
        {
            Valido="SI";
            res=1;
        }
        else
        {
            Valido= "NO";
            res=2;
        }
          try {
            
              
            Statement astmt = cn.createStatement();
            astmt.executeLargeUpdate("UPDATE cupones SET Descuento='"+txtNdesc.getText()+"' WHERE NombreCup='"+txtcup.getText()+"'");
          astmt.executeLargeUpdate("UPDATE cupones SET Validez='"+Valido+"' WHERE NombreCup='"+txtcup.getText()+"'");
            // mostrarDatos(txtNCupon.getText()); 
         JOptionPane.showMessageDialog(null, "Cupon actualizado correctamente"); 
     MostrarCupones();
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
  
          limpiarcajas();
    }//GEN-LAST:event_jButton3ActionPerformed

     void MostrarCupones(){   
     String[] titu= { "IdCupon","NombreCup", "Descuento", "Validez"};
     String[] registros;
        registros = new String[5];
     
     DefaultTableModel modelo= new DefaultTableModel(null,titu);
     
     String sql = "select * FROM cupones";
     
        try {
           Statement st= cn.createStatement();
           rs= st.executeQuery(sql);
           
           while(rs.next())
           {
              registros[0]= rs.getString("IdCupon");
               registros[1]= rs.getString("NombreCup");
               registros[2]= rs.getString("Descuento");
               registros[3]= rs.getString("Validez");
              
               
               modelo.addRow(registros);
           }
           
          jTable1.setModel(modelo);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos"+e.getMessage());
        }
    }
    
    
    
    private void txtNdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNdescActionPerformed

    private void radactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MActualizarCup;
    private javax.swing.JPanel MAlta;
    private javax.swing.JPanel MAltaCup;
    private javax.swing.JPanel MBaja;
    private javax.swing.JPanel MCupones;
    private javax.swing.JPanel MReporte;
    private javax.swing.JPanel MReporte1;
    private javax.swing.JPanel PanelActCup;
    private javax.swing.JPanel PanelActualizar;
    private javax.swing.JPanel PanelAlta;
    private javax.swing.JPanel PanelAltaCup;
    private javax.swing.JPanel PanelCupones;
    private javax.swing.JPanel PanelReportes;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAltaC;
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAct;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel min;
    private javax.swing.JCheckBox radActivo;
    private javax.swing.JCheckBox radact;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFechaAdq;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdprod;
    private javax.swing.JTextField txtNCupon;
    private javax.swing.JTextField txtNStock;
    private javax.swing.JTextField txtNdesc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcup;
    // End of variables declaration//GEN-END:variables
}
